# Generated by Django 5.0.6 on 2024-09-11 16:12

import django.db.models.deletion
import htdtech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_text', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Serialno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno_text', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_text', models.CharField(max_length=11, validators=[htdtech.models.validate_session])),
            ],
        ),
        migrations.CreateModel(
            name='Prevyearinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prospectus', models.FileField(upload_to='prospectus/')),
                ('Meritlist', models.FileField(upload_to='meritlist/')),
                ('Schedule', models.FileField(upload_to='schedule/')),
                ('Allottedlist', models.FileField(upload_to='Allottedlist/')),
                ('Amendments', models.FileField(upload_to='amendments/')),
                ('Cutoff', models.FileField(upload_to='cutoff/')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htdtech.course')),
                ('Serialno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htdtech.serialno')),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htdtech.session')),
            ],
        ),
    ]
