# Generated by Django 5.0.6 on 2024-09-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htdtech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Allottedlist',
            field=models.FileField(null=True, upload_to='Allottedlist/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Amendments',
            field=models.FileField(null=True, upload_to='amendments/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Cutoff',
            field=models.FileField(null=True, upload_to='cutoff/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Meritlist',
            field=models.FileField(null=True, upload_to='meritlist/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Prospectus',
            field=models.FileField(null=True, upload_to='prospectus/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Schedule',
            field=models.FileField(null=True, upload_to='schedule/'),
        ),
        migrations.AlterField(
            model_name='serialno',
            name='serialno_text',
            field=models.CharField(max_length=5),
        ),
    ]
