# Generated by Django 5.0.6 on 2024-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htdtech', '0002_alter_prevyearinfo_allottedlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Allottedlist',
            field=models.FileField(blank=True, null=True, upload_to='Allottedlist/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Amendments',
            field=models.FileField(blank=True, null=True, upload_to='amendments/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Cutoff',
            field=models.FileField(blank=True, null=True, upload_to='cutoff/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Meritlist',
            field=models.FileField(blank=True, null=True, upload_to='meritlist/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Prospectus',
            field=models.FileField(blank=True, null=True, upload_to='prospectus/'),
        ),
        migrations.AlterField(
            model_name='prevyearinfo',
            name='Schedule',
            field=models.FileField(blank=True, null=True, upload_to='schedule/'),
        ),
    ]
